### ISSUE TITLE
Unable to concat data and generate email in specific way 

### ISSUE THREAD

**Issue by maheshmanjunath01** [vincentrussell/json-data-generator#12]
Hello,

I am using json-data-generator for doing API automation testing, I am finding it more useful thanks for creating this.

I have below 2 issues: 

1) Just found that when I provide these functions it does not get replaced with respective function out put 

Functions used: 
{{date("java-simple-date-format")}}
{{concat("api",email{{"test.com"}})}}

in the output it just came the same as given above

Could you please let me know whether I am doing anything wrong ?

2) I can use fisrtname and lastname function to generate the name but if I want to generate an email with already generated firstname and lastname how can I do that 

Ex: {{firstname()}} : Tom
  {{lastname()}}: Daneils

Email need to be generated : Tom.Daniels@test.com 

It will be of great help if someone can answer above question 

version used : 1.5 
my data setup 
  public void jsondatasetup() {
      parser = new JsonDataGeneratorImpl();
      outputStream = new ByteArrayOutputStream();
      ((Map<?, ?>)ReflectionTestUtils.getField(Index.class,"STRING_INDEX_HOLDER_MAP")).clear();
      Approvals.setReporter(Reporters.console());
       }

Regards,
Mahesh

**Comment by vincentrussell** [comment]
I think this should work: {{concat(firstName(),".",lastName(),"@test.com")}}

**Comment by vincentrussell** [comment]
No.  it was never designed to save state, but maybe it would be a nice feature do something like: 

{
First name: {{put("firstName",firstName())}}
Last name:
Email:{{get("firstName")}}.lastname@test.com

**Comment by maheshmanjunath01** [comment]
Thank you again ! 
Just wanted to know if we want to generate the sequence number starting from 01018000

I tried with index and integer function it dint generate . It worked fine if I give 100/1000

Any advice on how to generate sequential numbers?

**Comment by vincentrussell** [comment]
the underlying data structure that it uses is integer so it wont support digits that start with zero.

You can always write a custom function to achieve something special like that.

**Comment by vincentrussell** [comment]
I just added get and put functions where you can do this:

{
  "firstName": "{{put("firstName", firstName())}}",
  "lastName": "{{put("lastName", lastName())}}",
  "email": "{{get("firstName")}}.{{get("lastName")}}@mydomain.com"
}

I'll release this later today or tomorrow if this meets your needs.

**Comment by maheshmanjunath01** [comment]
Yes please,  it will be of great help.
Thank you 
Mahesh

**Comment by vincentrussell** [comment]
OK.. i just released version 1.6.  It make take a few hours (at least) for the new jars to show up in maven central.

I upgraded guava as well so now json-data-generator depends on java 1.8.  I can't imagine this would be an issue given how old 1.7 and even 1.8 are at this point.

**Comment by maheshmanjunath01** [comment]
Ok thank you

**Comment by maheshmanjunath01** [comment]
Does this work for any other parameter as well? 

Is it built specifically for firstname and lastname ?

**Comment by maheshmanjunath01** [comment]
Great thank you!
