### ISSUE TITLE
Could {{uuid()}} provide the format without four hyphens?

### ISSUE THREAD

**Issue by andrew-qiu** [vincentrussell/json-data-generator#14]
The official example on the github page was provided like this:
{
    "id": "{{uuid()}}",
    "name": "A green door",
    "age": {{integer(1,50)}},
    "price": 12.50,
    "tags": ["home", "green"]
}

I noticed that the standard uuid displayed in five groups separated by hyphens. For example, 
123e4567-e89b-12d3-a456-426655440000

Sometimes I need the uuid format without four hyphens, like 123e4567e89b12d3a456426655440000, however. So could you please support this kind of uuid format.

**Comment by vincentrussell** [comment]
I just realized that you can use the hex function and specify 16 bytes: {{hex(16)}}

**Comment by vincentrussell** [comment]
just commited: 7df7e38ad63d65191fa729ff7b3fb67e333ccfe7

**Comment by andrew-qiu** [comment]
> just commited: [7df7e38](https://github.com/vincentrussell/json-data-generator/commit/7df7e38ad63d65191fa729ff7b3fb67e333ccfe7)

Thanks
