### ISSUE TITLE
Is there something wrong with processing Chinese ?

### ISSUE THREAD

**Issue by andrew-qiu** [vincentrussell/json-data-generator#16]
```java
String input = "{\"ss\":\"中文替换\"}";
Closer closer = Closer.create();
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
closer.register(outputStream);

JsonDataGeneratorImpl parser = new JsonDataGeneratorImpl();
try {
    parser.generateTestDataJson(jsonText, outputStream);
} catch (JsonDataGeneratorException e) {
    throw closer.rethrow(e);
} finally {
    closer.close();
}
System.out.println("Result: " + outputStream.toString("UTF-8"));
```

The output string appeared as gibberish:
Result: {"ss":"-��b"}

**Comment by andrew-qiu** [comment]
> Nope... it is not working with utf8. Hopefully this wont be too hard to fix.

Waiting for your good news ^o^

**Comment by vincentrussell** [comment]
Ok.  This was a very important bug.  Thank you for finding this.   See commit: 2e1ab569a54f09637807480afb5090c19de39f47

Let me know if everything seems good for you and I will push release 1.7 to maven central.

Thanks,
Vincent

**Comment by andrew-qiu** [comment]
> Ok. This was a very important bug. Thank you for finding this. See commit: [2e1ab56](https://github.com/vincentrussell/json-data-generator/commit/2e1ab569a54f09637807480afb5090c19de39f47)
> 
> Let me know if everything seems good for you and I will push release 1.7 to maven central.
> 
> Thanks,
> Vincent

Everything seems to be fine. No extra bugs were found these days.
