### ISSUE TITLE
addMethod() cannot handle different date formats

### ISSUE THREAD

**Issue by anoopk1981** [vincentrussell/json-data-generator#27]
Hi,

  I have key value pairs as below..

   ```
    {
   "user_date": "{{put("date", date("MMddyyyyHHmmss"))}}",
   "event_date": "{{addDays(get("date"), 12)}}"
   }
  ```
 If I try to generate data for the above json I get the error as below
 ```
Unexpected character (d) at position 5581.
	at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
 ``` 

The user_date field is set correctly as "04232021180201" but it is failing in addDays()

Thank You

**Comment by vincentrussell** [comment]
So it looks like what is failing is that you are not passing in the date format into the addDays function, by default the addMethod uses the following format: dd-MM-yyyy HH:mm:ss.  The following json worked for me.   Please let me know if the following works:

{
  "user_date": "{{put("date", date("MMddyyyyHHmmss"))}}",
  "event_date": "{{addDays("MMddyyyyHHmmss", get("date"), 12)}}"
}


I'm going to see if I can figure out a way to make the error more obvious.

**Comment by anoopk1981** [comment]
The syntax that you provided worked. Thank You. On a related note if I have to do the same addDays but without referencing another field what will be the syntax? For example if I want to add 12 days to the current date how can I do that? I tried "event_date": "{{addDays("MMddyyyyHHmmss", date(), 12)}}" but that didnt work.

**Comment by vincentrussell** [comment]
the date() function by itself uses this simpleFormat; "EEE, d MMM yyyy HH:mm:ss z"

So you would need to do date("MMddyyyyHHmmss")

**Comment by anoopk1981** [comment]
yes. This worked. Thank You. Closing this thread. 

```
"{{addDays("MMddyyyyHHmmss", date("MMddyyyyHHmmss"), 12)}}"
```
