### ISSUE TITLE
Trying to generate the Output json But its not working for me 

### ISSUE THREAD

**Issue by dillipkumarpradhan** [vincentrussell/json-data-generator#29]
Input file :test.json
{
  "id": "{{uuid()}}",
  "name": "A green door",
  "age": {{integer(1,50)}},
"price": 12.50,
"tags": ["home", "green"]
}

Code 

    File file= new File("src/test/resources/testData/test.json");
      OutputStream out = new FileOutputStream("test2.json");
      JsonDataGeneratorImpl parser = new JsonDataGeneratorImpl();
      parser.generateTestDataJson(file, out);

Output file : test2.json

{
  "id": "{{uuid()}}",
  "name": "A green door",
  "age": {{integer(1,50)}},
"price": 12.50,
"tags": ["home", "green"]
}

**Comment by vincentrussell** [comment]
Is the encoding of your file UTF-8?   That's the only thing that I can think of because what you did should work.  If you look at the tests in JsonDataGeneratorTest, this is essentially what it does.

**Comment by dillipkumarpradhan** [comment]
No

**Comment by vincentrussell** [comment]
ok.  so try it with a utf-8 file.
