### ISSUE TITLE
Get and Put method not working for JSON

### ISSUE THREAD

**Issue by fivetran-shubhamjoshi** [vincentrussell/json-data-generator#30]
Both case input JSON

    {
      "firstName": "{{put("firstName", firstName())}}",
      "lastName": "{{put("lastName", lastName())}}",
      "email": "{{get("firstName")}}.{{get("lastName")}}@mydomain.com"
    },

    {
      "firstName": "{{put(\"firstName\", firstName())}}",
      "lastName": "{{put(\"lastName\", lastName())}}",
      "email": "{{get(\"firstName\")}}.{{get(\"lastName\")}}@mydomain.com"
    },

JSON Response also attached

![image](https://user-images.githubusercontent.com/85578087/127213516-03f4c619-441a-48b0-9601-077989ed8f90.png)

**Comment by vincentrussell** [comment]
Can you share your entire json?
I tried the following input and it worked just fine:
{
    "id": "dfasf235345345",
    "name": "A green door",
    "age": 23,
    "price": 12.50,
    "colors": ['{{repeat(4)}}',
        {
            "firstName": "{{put("firstName", firstName())}}",
            "lastName": "{{put("lastName", lastName())}}",
            "email": "{{get("firstName")}}.{{get("lastName")}}@mydomain.com"
        }
    ]
}


rendered as:


{
    "id": "dfasf235345345",
    "name": "A green door",
    "age": 23,
    "price": 12.50,
    "colors": [
        {
            "firstName": "Nicole",
            "lastName": "Beck",
            "email": "Nicole.Beck@mydomain.com"
        },

        {
            "firstName": "Jodie",
            "lastName": "Lester",
            "email": "Jodie.Lester@mydomain.com"
        },

        {
            "firstName": "Carly",
            "lastName": "Cobb",
            "email": "Carly.Cobb@mydomain.com"
        },

        {
            "firstName": "Holland",
            "lastName": "Levine",
            "email": "Holland.Levine@mydomain.com"
        }
    ]
}

**Comment by fivetran-shubhamjoshi** [comment]
Yeah It worked for me too there was a config issue it seems

**Comment by fivetran-shubhamjoshi** [comment]
Thanks alot for quick Response.😊
