### ISSUE TITLE
Multi Thread support in JsonDataGeneratorImpl

### ISSUE THREAD

**Issue by Fivetran-Nikunjkumar** [vincentrussell/json-data-generator#31]
The code in JsonDataGeneratorImpl is mostly single-threaded and thus makes it very slow for generating large data sets.
Can you please improve it by introducing multi-threading?

**Comment by vincentrussell** [comment]
ok checkout release 1.13 and let me know if that is working of you.  I wrote some multi-threaded unit tests and they appear to work pretty well.
