### ISSUE TITLE
Generate timestamp in seconds instead of miliseconds

### ISSUE THREAD

**Issue by gabriel-augusto** [vincentrussell/json-data-generator#35]
Hi, is there any way to generate the timestamp in seconds instead of milliseconds using the {{timestamp()}} function?

**Comment by gabriel-augusto** [comment]
I would like to help with this implementation. [This is a draft](https://github.com/vincentrussell/json-data-generator/pull/36) of how I imagine it works. Would you help me to validate if I'm doing it right and how to test this PR?

**Comment by vincentrussell** [comment]
Thank you for the contribution... i will take a look at the merge request.

**Comment by vincentrussell** [comment]
Take a look at my changes and let me know if that works for you.  I'll cut a release if you need.

Thanks,
