### ISSUE TITLE
addYears() always taking date format as "dd-MM-yyyy HH:mm:ss"

### ISSUE THREAD

**Issue by deepakmittal888** [vincentrussell/json-data-generator#37]
I want future date of 10 years in addition to today's date in a specific format.

I did try {{addYears("MM/dd/yyyy",date(),10)}} , but unfortunately it didn't work.

The work around I got is:

{{dateFormat(addYears(date("dd-MM-yyyy HH:mm:ss"), 10),"dd-MM-yyyy HH:mm:ss","MM/dd/yyyy")}}

Should it be like it only or I am doing something wrong?

Thanks and yeah I really liked your library.

**Comment by vincentrussell** [comment]
I'm glad you like the library.  So the some of the functions take dates in a certain format or require that you specify the date/time format  so I believe that the way that you have done it is the only way possible.

I believe that the date stuff could stand to be cleaned up some.
