### ISSUE TITLE
Can't create randon date between two dates.

### ISSUE THREAD

**Issue by eblucas-wtc** [vincentrussell/json-data-generator#38]
Trying to create random date but I'm not getting the desired output.

Creating only a single date with todays date works fine.

config file
`{
  "Date": "{{date('dd-MM-yyyy')}}",
  "DateRange": "{{date('01-01-2020 00:00:00','10-05-2022 00:00:00','dd-MM-yyyy'}}",`

Output

`{"Date":"20-05-2022",
"DateRange":"{{date('01-01-2020 00:00:00','10-05-2022 00:00:00','dd-MM-yyyy'}}",`

**Comment by eblucas-wtc** [comment]
I'm using with GCP Dataflow - this is my json file.

```
{
  "DateRange": "{{date('10-01-2022 10:20:23','20-01-2022 10:20:23'}}",
  "PageId": "P-{{alphaNumeric(10)}}",
  "Sessions" : "{{integer(5,1000)}}",
  "NewUsers" : "{{integer(1,1000)}}",
  "Users" : "{{integer(1,1000)}}",
  "Channel" : "{{random('Direct','Email','Social Network','Referral','Ads')}}",
  "Clicks" : "{{integer(1,1000)}}",
  "DataType" : "Test Data"
}
```

All fields are working fine but the DateRange one.  THe output is just the same string in the config file

**Comment by vincentrussell** [comment]
I believe this is because your date format doesn't match the date that you are passing in.

Please review the docs:
current date date (default format is: EEE, d MMM yyyy HH:mm:ss z):

{{date()}}
current date with format:

{{date("java-simple-date-format")}}
random date between two dates with format (your input must be in this format dd-MM-yyyy HH:mm:ss):

{{date("begin-date","end-date","java-simple-date-format"}}
random date between two dates with default format (your input must be in this format EEE, d MMM yyyy HH:mm:ss z):

{{date("begin-date","end-date"}}

**Comment by eblucas-wtc** [comment]
Hi Thanks for replying

Docs says - 
```

random date between two dates with format (your input must be in this format dd-MM-yyyy HH:mm:ss):

{{date("begin-date","end-date","java-simple-date-format"}}
```

I tried using  EEE, d MMM yyyy HH:mm:ss z as well

 "DateRange": "{{date('Mon, 16 May 2022 05:06:16 +0100','Mon, 16 May 2022 05:06:16 +0100','dd-MM-yyyy'}}",

But it didnt work, can you spot where I'm mistaken?

Thanks once again

**Comment by eblucas-wtc** [comment]
Tried 

`  "DateRange": "{{date('Mon, 03 Jan 2022 05:06:16 UTC','Mon, 16 May 2022 05:06:16 UTC','dd-MM-yyyy'}}",`.  

and

`  "DateRange": "{{date('Mon, 03 Jan 2022 05:06:16 +0100','Mon, 16 May 2022 05:06:16 +0100','dd-MM-yyyy'}}",`
 
But the output still wrong.

Thanks for the lib btw, very usefull

**Comment by vincentrussell** [comment]
I just looked at the DefaultFuntionTest:


looks like the input format has to be: dd-MM-yyyy HH:mm:ss  and then you can provide an optional output format if you need to change that.

   @Test
    public void dateWithinRange() throws ParseException, InvocationTargetException, IllegalAccessException {
        String dateFormatText = "EEE, d MMM yyyy HH:mm:ss z";
        SimpleDateFormat dateFormat = new SimpleDateFormat(dateFormatText);
        String result = functionRegistry.executeFunction("date", "06-16-1956 12:00:00", "06-16-1975 12:00:00");
        java.util.Date date = dateFormat.parse(result);
        assertNotNull(date);
    }

**Comment by eblucas-wtc** [comment]
Hi @vincentrussell  Thanks for getting back to me.

I tried with the input format `dd-MM-yyyy HH:mm:ss` as well but it didnt work either.

`
  "DateRange": "{{date('10-01-2022 10:20:23','20-01-2022 10:20:23'}}",`

also tried providing the output format

`  "DateRange": "{{date('10-01-2022 10:20:23','20-01-2022 10:20:23', 'dd-MM-yyyy'}}",`

**Comment by vincentrussell** [comment]
dd-MM-yyyy

it looks like you are putting in MM-dd-yyyy

**Comment by vincentrussell** [comment]
i'm sorry you are right..  let me write a test

**Comment by eblucas-wtc** [comment]
no need to be sorry :P 

Thanks for helping me.

This is my last test

Input
`{
  "Date": "{{date('01-01-2020 12:00:00 ','01-01-2021 12:00:00','dd-MM-yyyy'}}",
  "PageId": "P-{{alphaNumeric(10)}}",
  "Sessions" : "{{integer(5,1000)}}",
  "NewUsers" : "{{integer(1,1000)}}",
  "Users" : "{{integer(1,1000)}}",
  "Channel" : "{{random('Direct','Email','Social Network','Referral','Ads')}}",
  "Clicks" : "{{integer(1,1000)}}",
  "DataType" : "Test Data"
}`


output

`{"Date":"{{date('01-01-2020 12:00:00 ','01-01-2021 12:00:00','dd-MM-yyyy'}}","PageId":"P-g1QE9bV7v2","Sessions":"394","NewUsers":"298","Users":"790","Channel":"Ads","Clicks":"274","DataType":"Test Data"}`

**Comment by vincentrussell** [comment]
you are missing a closing paren in your date function

"DateRange": "{{date('10-01-2022 10:20:23','20-01-2022 10:20:23','dd-MM-yyyy'**)**}}

**Comment by eblucas-wtc** [comment]
Wowwwww... 
Now I say I'm sorry. 

Wasted 4 hours because of a parentheses 

Thank you very much and sorry for this embarrassing  "issue"  I created here :P

**Comment by eblucas-wtc** [comment]
Thanks, I wil close this and leave in case someone else forget a parenthesis

**Comment by eblucas-wtc** [comment]
Hi @vincentrussell 

I noticed that the parenthesis is missing in the documentation in a few examples. Just to let you know so you can update it.

Thanks

**Comment by vincentrussell** [comment]
Thanks.. i already noticed that and fixed it earlier today.
