### ISSUE TITLE
How to get the updated sample file indexes after data generation.

### ISSUE THREAD

**Issue by Fivetran-Nikunjkumar** [vincentrussell/json-data-generator#40]
In my case, I am writing a utility that will start every day and generate data from where it left last day. This means if we have an index tag, and I generated 10 records on day 1 so record values would be 1-10 then want to generate records on day 2 with a new process, but the value should start from 11 next day. So I want to store the updated sample or indexes which I think you are creating somewhere. Can we access that updated sample file and store it and next day use it to generate the records.

I did a little debugging and found that all the indexes are stored in` static final Map<String, IndexHolder> STRING_INDEX_HOLDER_MAP = new ConcurrentHashMap();` in Index class. Can you please provide a getter and setter for this map so that we can set it before starting the execution and save its state at the end of execution for the next day.

**Comment by vincentrussell** [comment]
why don't you just update the source file each day and modify the starting index with the following function:

{{index("index-name",78)}

I"m not too fond of the idea of providing a getter and setter to a static class

**Comment by Fivetran-Nikunjkumar** [comment]
> 
I already did the same, but there are many scenarios like- resetIndex, multiple ways to define an index, multiple indexes inside a very complex nested JSON, Repeat tags at multiple levels inside that JSON, and indexes inside jsonArrays that too repeat in a nested hierarchy. So the logic that I written is becoming complex and flaky over the time. I thought of making it better and found that I should read it from this hashMap. Hope you understand and make it better.

**Comment by vincentrussell** [comment]
You are more than welcome to make your own index2 function (or some better name) and register that with the FunctionRegistry.   If you can do that you can give access to whatever you want in that class.
