### ISSUE TITLE
Is there any way to pass the number in Repeat tag at run time?

### ISSUE THREAD

**Issue by deepakmittal888** [vincentrussell/json-data-generator#41]
Hi, I am using repeat tag in my json file but the problem I am facing that I've to set the number in it before compiling as there is no way I can pass it at run time.

Can you please make it more dynamic so that anyone can set the number inside repeat tag at runtime?

**Comment by vincentrussell** [comment]
I think i can probably introduce a systemProperty('myProperty') function or something similar that would allow you to drop in system properties via -DmyProperty=2313

I am not sure when I'll get to this though.

**Comment by vincentrussell** [comment]
Ok...

I think this might work for you:

https://github.com/vincentrussell/json-data-generator/compare/master...system-property-function

**Comment by deepakmittal888** [comment]
Thanks for making repeats tag a function. When you're going to merge it in main branch so that I can take the latest pull?

AND Highly appreciated for the fix. 👍

**Comment by vincentrussell** [comment]
just released 1.16.... will take a few hours before it shows up in maven central.
