### ISSUE TITLE
Integer and Boolean data types

### ISSUE THREAD

**Issue by spojg** [vincentrussell/json-data-generator#43]
This tool is returning any data type value as String. Is it possible to return value as it is instead of String .

**Comment by spojg** [comment]
Example: {{bool()}} return as false instead of “false”.

**Comment by spojg** [comment]
I’m using your tool to generate positive request payload. For data type Integer or Boolean , in payload value should be number/Boolean should as 11/false without quotes .

**Comment by spojg** [comment]
Could you please give some advice Where exactly in your code fields are surrounded with  quotes. I’m trying to figure out.

**Comment by vincentrussell** [comment]
You have to put the quotes yourself in your json.

like this:
{
    "day1": "{{put("date", date("dd-MM-yyyy HH:mm:ss"))}}",
    "day2": "{{addDays(get("date"), 12)}}"
}


Please look at the unit tests

**Comment by spojg** [comment]
I got it , Thank you for the advice.
